import React from 'react';
import Header from '../component/Header';
import oc from "../img/OC.jpg";
import Qr from '../component/Qr';

const Faq = () => {
    return (
        <div>
            <Header title="FAQ" description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Arcu cursus euismod quis viverra. Consequat ac felis donec et odio pellentesque. Tristique sollicitudin nibh sit amet commodo nulla. In hendrerit gravida rutrum quisque non. Bibendum ut tristique et egestas. Justo donec enim diam vulputate. Mauris augue neque gravida in fermentum et sollicitudin. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Mauris pharetra et ultrices neque ornare aenean euismod elementum nisi. Duis convallis convallis tellus id interdum velit. Phasellus faucibus scelerisque eleifend donec. Urna cursus eget nunc scelerisque viverra mauris. Lacinia at quis risus sed. Aliquam vestibulum morbi blandit cursus risus at." url={oc}/>
            {/* <h1>FAQ</h1> */}
            <Qr q="Question n°1" r="Tortor vitae purus faucibus ornare suspendisse sed nisi. Egestas egestas fringilla phasellus faucibus scelerisque. Aenean vel elit scelerisque mauris pellentesque pulvinar. Purus gravida quis blandit turpis. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Vitae justo eget magna fermentum iaculis eu non diam phasellus. Semper risus in hendrerit gravida rutrum quisque non. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Viverra nam libero justo laoreet sit amet cursus sit amet. Mauris pharetra et ultrices neque. Erat pellentesque adipiscing commodo elit at. Eros in cursus turpis massa tincidunt. Vitae elementum curabitur vitae nunc. Vivamus arcu felis bibendum ut tristique et egestas quis. Lobortis feugiat vivamus at augue. Libero id faucibus nisl tincidunt. Tincidunt praesent semper feugiat nibh sed pulvinar proin." id="1"></Qr>
            <Qr q="Question n°2" r="Tortor vitae purus faucibus ornare suspendisse sed nisi. Egestas egestas fringilla phasellus faucibus scelerisque. Aenean vel elit scelerisque mauris pellentesque pulvinar. Purus gravida quis blandit turpis. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Vitae justo eget magna fermentum iaculis eu non diam phasellus. Semper risus in hendrerit gravida rutrum quisque non. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Viverra nam libero justo laoreet sit amet cursus sit amet. Mauris pharetra et ultrices neque. Erat pellentesque adipiscing commodo elit at. Eros in cursus turpis massa tincidunt. Vitae elementum curabitur vitae nunc. Vivamus arcu felis bibendum ut tristique et egestas quis. Lobortis feugiat vivamus at augue. Libero id faucibus nisl tincidunt. Tincidunt praesent semper feugiat nibh sed pulvinar proin." id="2"></Qr>
            <Qr q="Question n°3" r="Tortor vitae purus faucibus ornare suspendisse sed nisi. Egestas egestas fringilla phasellus faucibus scelerisque. Aenean vel elit scelerisque mauris pellentesque pulvinar. Purus gravida quis blandit turpis. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Vitae justo eget magna fermentum iaculis eu non diam phasellus. Semper risus in hendrerit gravida rutrum quisque non. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Viverra nam libero justo laoreet sit amet cursus sit amet. Mauris pharetra et ultrices neque. Erat pellentesque adipiscing commodo elit at. Eros in cursus turpis massa tincidunt. Vitae elementum curabitur vitae nunc. Vivamus arcu felis bibendum ut tristique et egestas quis. Lobortis feugiat vivamus at augue. Libero id faucibus nisl tincidunt. Tincidunt praesent semper feugiat nibh sed pulvinar proin." id="3"></Qr>
            <Qr q="Question n°4" r="Tortor vitae purus faucibus ornare suspendisse sed nisi. Egestas egestas fringilla phasellus faucibus scelerisque. Aenean vel elit scelerisque mauris pellentesque pulvinar. Purus gravida quis blandit turpis. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Vitae justo eget magna fermentum iaculis eu non diam phasellus. Semper risus in hendrerit gravida rutrum quisque non. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Viverra nam libero justo laoreet sit amet cursus sit amet. Mauris pharetra et ultrices neque. Erat pellentesque adipiscing commodo elit at. Eros in cursus turpis massa tincidunt. Vitae elementum curabitur vitae nunc. Vivamus arcu felis bibendum ut tristique et egestas quis. Lobortis feugiat vivamus at augue. Libero id faucibus nisl tincidunt. Tincidunt praesent semper feugiat nibh sed pulvinar proin." id="4"></Qr>
            <Qr q="Question n°5" r="Tortor vitae purus faucibus ornare suspendisse sed nisi. Egestas egestas fringilla phasellus faucibus scelerisque. Aenean vel elit scelerisque mauris pellentesque pulvinar. Purus gravida quis blandit turpis. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Vitae justo eget magna fermentum iaculis eu non diam phasellus. Semper risus in hendrerit gravida rutrum quisque non. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Pretium viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Viverra nam libero justo laoreet sit amet cursus sit amet. Mauris pharetra et ultrices neque. Erat pellentesque adipiscing commodo elit at. Eros in cursus turpis massa tincidunt. Vitae elementum curabitur vitae nunc. Vivamus arcu felis bibendum ut tristique et egestas quis. Lobortis feugiat vivamus at augue. Libero id faucibus nisl tincidunt. Tincidunt praesent semper feugiat nibh sed pulvinar proin." id="5"></Qr>
        </div>
    );
};

export default Faq;